### ISSUE TITLE
Cannot upload pfp

### ISSUE THREAD

**Issue by Spider670** [wavy/wavyfm-docs#28]
![Screenshot_20210314-190530](https://user-images.githubusercontent.com/80656555/111091995-15b12f00-850b-11eb-925a-3dac0ff80d27.png)
I could not upload a pfp to my profile despite the picture meeting the parameters and being a jpeg image. Tried both on my desktop and on mobile with a handful of images. Nothing seems to be going through, it kind of greys out like in the image provided.

**Comment by aramperes** [comment]
Hi there, it seems one of the images you tried to upload earlier caused an internal crash. The avatar function is currently down for maintenance. I'll update you when things go back to normal.

Thanks

**Comment by Spider670** [comment]
Oh jeez, i'm sorry if I messed that up and thanks for the response.

**Comment by aramperes** [comment]
No problem, it's why we do this! Feel free to try uploading avatars again. If it's causing more issues I'll investigate further.

**Comment by Spider670** [comment]
Will do, thanks!
